lib: [
  "_build/install/default/lib/npy/npy.cmxs"
  "_build/install/default/lib/npy/npy.a"
  "_build/install/default/lib/npy/npy.cmxa"
  "_build/install/default/lib/npy/npy.cma"
  "_build/install/default/lib/npy/npy.mli"
  "_build/install/default/lib/npy/npy.cmti"
  "_build/install/default/lib/npy/npy.cmt"
  "_build/install/default/lib/npy/npy.cmx"
  "_build/install/default/lib/npy/npy.cmi"
  "_build/install/default/lib/npy/opam" {"opam"}
  "_build/install/default/lib/npy/META" {"META"}
]
doc: [
  "_build/install/default/doc/npy/LICENSE"
  "_build/install/default/doc/npy/README.md"
]
